using STRIDE.Modules.Reporting.Application.ReadModels;

namespace STRIDE.Modules.Reporting.Application.Abstractions;

/// <summary>
/// Read-side reporting service: Dapper projections over the workflows and reporting schemas.
/// All methods are tenant-scoped.
/// </summary>
public interface IReportingReadService
{
    /// <summary>
    /// Returns the aggregated KPI snapshot for the dashboard header row.
    /// </summary>
    Task<DashboardKpiDto> GetDashboardKpisAsync(Guid tenantId, CancellationToken ct = default);

    /// <summary>
    /// Returns daily workflow activity trend for the last <paramref name="days"/> days.
    /// </summary>
    Task<IReadOnlyList<WorkflowTrendDto>> GetWorkflowTrendsAsync(
        Guid tenantId,
        int days = 30,
        CancellationToken ct = default);

    /// <summary>
    /// Returns a summary list of all reports generated by the tenant.
    /// </summary>
    Task<IReadOnlyList<ReportSummaryDto>> GetReportSummariesAsync(
        Guid tenantId,
        CancellationToken ct = default);

    /// <summary>
    /// Returns per-definition instance counts broken down by state.
    /// Used to power the Workflow Summary report type.
    /// </summary>
    Task<IReadOnlyList<WorkflowSummaryReportRowDto>> GetWorkflowSummaryAsync(
        Guid tenantId,
        CancellationToken ct = default);
}
